### ISSUE TITLE
Not compile with tide 0.15

### ISSUE THREAD

**Issue by fiag** [Fishrock123/tide-compress#5]
```
error[E0277]: expected a `Fn<(tide::Request<state::State>, Next<'a, state::State>)>` closure, found `CompressMiddleware`
  --> src/app.rs:30:14
   |
30 |     app.with(tide_compress::CompressMiddleware::new()); // Outgoing compression middleware
   |              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected an `Fn<(tide::Request<state::State>, Next<'a, state::State>)>` closure, found `CompressMiddleware`
   |
   = help: the trait `for<'a> Fn<(tide::Request<state::State>, Next<'a, state::State>)>` is not implemented for `CompressMiddleware`
   = note: required because of the requirements on the impl of `Middleware<state::State>` for `CompressMiddleware`
```

but works with tide 0.14.
rustc 1.48.0-nightly (1fd5b9d51 2020-09-20)

**Comment by Fishrock123** [comment]
:raised_eyebrow: 

That's a very odd error. Are you sure you are running Tide 0.15? What happen after you do `cargo update`?

I can't reproduce locally.

**Comment by Fishrock123** [comment]
Ohhhh 0.14 probably isn't compatible with 0.15 yeah? So I guess i need to release a new version of `tide-compress` after all...

**Comment by Fishrock123** [comment]
Fixed in [0.8.0](https://github.com/Fishrock123/tide-compress/releases/tag/0.8.0). Thanks for noticing this!
